#!/usr/bin/env python3
"""Refresh essay order and older/newer links in content frontmatter."""

import html
import re
from pathlib import Path

from essay_content import CONTENT, read_content, write_content


def nav(older, newer):
    parts = []
    if older:
        parts.append(
            f'          <a class="older" href="/essays/{older["slug"]}"><span class="label">older</span>← {html.escape(older["title"])}</a>'
        )
    if newer:
        parts.append(
            f'          <a class="newer" href="/essays/{newer["slug"]}"><span class="label">newer</span>{html.escape(newer["title"])} →</a>'
        )
    block = "        <!-- essay-nav: generated by tools/link-essays.py -->\n"
    if parts:
        block += '        <nav class="essay-nav" aria-label="older and newer essays">\n' + "\n".join(parts) + "\n        </nav>\n"
    return block + "        <!-- /essay-nav -->"


def main():
    records = [(path, *read_content(path)) for path in CONTENT.glob("*.md")]
    records.sort(key=lambda record: (record[1]["date"], record[1]["slug"]), reverse=True)
    for i, (path, metadata, markdown) in enumerate(records):
        older = records[i + 1][1] if i + 1 < len(records) else None
        newer = records[i - 1][1] if i else None
        metadata["order"] = i
        metadata["older"] = older["slug"] if older else ""
        metadata["newer"] = newer["slug"] if newer else ""
        updated, count = re.subn(
            r"        <!-- essay-nav: generated by tools/link-essays\.py -->\n.*?<!-- /essay-nav -->",
            nav(older, newer),
            metadata["afterArticleHtml"],
            flags=re.S,
        )
        if count != 1:
            raise ValueError(f"missing essay nav markers: {path}")
        metadata["afterArticleHtml"] = updated
        write_content(metadata["slug"], metadata, markdown)
        print(f'{metadata["slug"]}: older={metadata["older"] or "-"} newer={metadata["newer"] or "-"}')


if __name__ == "__main__":
    main()
