#!/usr/bin/env python3
"""refresh the older/newer footer nav on every essay page.

reads the order from essays.html (newest first) and rewrites the block between
<!-- essay-nav --> markers in each essays/<slug>.html. run it after importing
or reordering an essay. no arguments, no dependencies.
"""

import html
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

index = open(os.path.join(ROOT, "essays.html")).read()
entries = re.findall(r'<a href="/essays/([a-z0-9-]+)">([^<]+)</a>', index)
seen, order = set(), []
for slug, title in entries:
    if slug not in seen:
        seen.add(slug)
        order.append((slug, html.unescape(title.strip())))

for i, (slug, title) in enumerate(order):
    newer = order[i - 1] if i > 0 else None
    older = order[i + 1] if i + 1 < len(order) else None
    parts = []
    if older:
        parts.append(
            f'          <a class="older" href="/essays/{older[0]}"><span class="label">older</span>← {html.escape(older[1])}</a>'
        )
    if newer:
        parts.append(
            f'          <a class="newer" href="/essays/{newer[0]}"><span class="label">newer</span>{html.escape(newer[1])} →</a>'
        )
    block = "        <!-- essay-nav: generated by tools/link-essays.py -->\n"
    if parts:
        block += '        <nav class="essay-nav" aria-label="older and newer essays">\n' + "\n".join(parts) + "\n        </nav>\n"
    block += "        <!-- /essay-nav -->"
    path = os.path.join(ROOT, "essays", f"{slug}.html")
    page = open(path).read()
    new = re.sub(r"        <!-- essay-nav: generated by tools/link-essays\.py -->\n.*?<!-- /essay-nav -->", block, page, flags=re.S)
    if new == page and block not in page:
        raise SystemExit(f"{path}: no essay-nav markers found")
    open(path, "w").write(new)
    print(f"{slug}: older={older[0] if older else '-'} newer={newer[0] if newer else '-'}")
